import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
const MyApp({ Key? key }) : super(key: key);

  @override
  Widget build(BuildContext context){
    return MaterialApp(      
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App')
          ),
        body: Container(
          margin: EdgeInsets.only(left: 30, right: 30, top: 20),
          color: Colors.grey,          
          child:  Center(
            child: Column(
              children: [
                const Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text("Muchson"),
                    Text("Muchson")
                  ],
                ),
                SizedBox(height: 50,),
                const Text("List Anak Didik"),
                SizedBox(                  
                  height: 200,
                  child: ListView(
                    padding: const EdgeInsets.all(10),
                    children: const [
                    Text('ADE ALI INDRA'),
                    Text('ALWIN ZUHRIANDI MANALU'),
                    Text('ANISA YUNIARTI'),
                    Text('Bima Pangestu Nugraha'),
                    Text('Dastin Pranata Yuda'),
                    Text('David Christian Hui'),
                    Text('David Liem'),
                    Text('Delia Sepiana'),
                    Text('FAJRUL KAMAL'),
                    Text('GHAZI FARHANU DISASMORO'),
                    Text('HIDAYAH DANIAWATI'),
                    Text('JUHARMANSAH'),
                    Text('KATARINA ANDREA LAURENTIA'),
                    Text('MUHAMMAD AFRIZAL RASYID'),
                    Text('MUHAMMAD ARARYA HAFIZH ATHALLA'),
                    Text('MUHAMMAD ILHAM'),
                    Text('MUHAMMAD NGURAH ARYA PRATAMA'),
                    Text('MUSTIKA CHAIRANI'),
                    Text('NURMALASARI'),
                    Text('Phrimus Nufeto'),
                    Text('PUTRI DIANA HAFSYAWATI'),
                    Text('RACHAEL NATHASYA'),
                    Text('RAFI TAUFIQURAHMAN'),
                    Text('RAMADHAN PUTRA NUGRAHA'),
                    Text('YUNITA ANGGERAINI'),
                    Text('ADE ALI INDRA'),
                    Text('ALWIN ZUHRIANDI MANALU'),
                    Text('ANISA YUNIARTI'),
                    Text('Bima Pangestu Nugraha'),
                    Text('Dastin Pranata Yuda'),
                    Text('David Christian Hui'),
                    Text('David Liem'),
                    Text('Delia Sepiana'),
                    Text('FAJRUL KAMAL'),
                    Text('GHAZI FARHANU DISASMORO'),
                    Text('HIDAYAH DANIAWATI'),
                    Text('JUHARMANSAH'),
                    Text('KATARINA ANDREA LAURENTIA'),
                    Text('MUHAMMAD AFRIZAL RASYID'),
                    Text('MUHAMMAD ARARYA HAFIZH ATHALLA'),
                    Text('MUHAMMAD ILHAM'),
                    Text('MUHAMMAD NGURAH ARYA PRATAMA'),
                    Text('MUSTIKA CHAIRANI'),
                    Text('NURMALASARI'),
                    Text('Phrimus Nufeto'),
                    Text('PUTRI DIANA HAFSYAWATI'),
                    Text('RACHAEL NATHASYA'),
                    Text('RAFI TAUFIQURAHMAN'),
                    Text('RAMADHAN PUTRA NUGRAHA'),
                    Text('YUNITA ANGGERAINI'),
                    Text('ADE ALI INDRA'),
                    Text('ALWIN ZUHRIANDI MANALU'),
                    Text('ANISA YUNIARTI'),
                    Text('Bima Pangestu Nugraha'),
                    Text('Dastin Pranata Yuda'),
                    Text('David Christian Hui'),
                    Text('David Liem'),
                    Text('Delia Sepiana'),
                    Text('FAJRUL KAMAL'),
                    Text('GHAZI FARHANU DISASMORO'),
                    Text('HIDAYAH DANIAWATI'),
                    Text('JUHARMANSAH'),
                    Text('KATARINA ANDREA LAURENTIA'),
                    Text('MUHAMMAD AFRIZAL RASYID'),
                    Text('MUHAMMAD ARARYA HAFIZH ATHALLA'),
                    Text('MUHAMMAD ILHAM'),
                    Text('MUHAMMAD NGURAH ARYA PRATAMA'),
                    Text('MUSTIKA CHAIRANI'),
                    Text('NURMALASARI'),
                    Text('Phrimus Nufeto'),
                    Text('PUTRI DIANA HAFSYAWATI'),
                    Text('RACHAEL NATHASYA'),
                    Text('RAFI TAUFIQURAHMAN'),
                    Text('RAMADHAN PUTRA NUGRAHA'),
                    Text('YUNITA ANGGERAINI'),
                    Text('ADE ALI INDRA'),
                    Text('ALWIN ZUHRIANDI MANALU'),
                    Text('ANISA YUNIARTI'),
                    Text('Bima Pangestu Nugraha'),
                    Text('Dastin Pranata Yuda'),
                    Text('David Christian Hui'),
                    Text('David Liem'),
                    Text('Delia Sepiana'),
                    Text('FAJRUL KAMAL'),
                    Text('GHAZI FARHANU DISASMORO'),
                    Text('HIDAYAH DANIAWATI'),
                    Text('JUHARMANSAH'),
                    Text('KATARINA ANDREA LAURENTIA'),
                    Text('MUHAMMAD AFRIZAL RASYID'),
                    Text('MUHAMMAD ARARYA HAFIZH ATHALLA'),
                    Text('MUHAMMAD ILHAM'),
                    Text('MUHAMMAD NGURAH ARYA PRATAMA'),
                    Text('MUSTIKA CHAIRANI'),
                    Text('NURMALASARI'),
                    Text('Phrimus Nufeto'),
                    Text('PUTRI DIANA HAFSYAWATI'),
                    Text('RACHAEL NATHASYA'),
                    Text('RAFI TAUFIQURAHMAN'),
                    Text('RAMADHAN PUTRA NUGRAHA'),
                    Text('YUNITA ANGGERAINI'),
                    ],
                  ),
                ),
                SizedBox(height: 50,),
                SizedBox(                  
                  height: 200,
                  child: GridView.count(                                                            
                    crossAxisCount: 2,
                    children: const [
                    Text('ADE ALI INDRA'),
                    Text('ALWIN ZUHRIANDI MANALU'),
                    Text('ANISA YUNIARTI'),
                    Text('Bima Pangestu Nugraha'),
                    Text('Dastin Pranata Yuda'),
                    Text('David Christian Hui'),
                    Text('David Liem'),
                    Text('Delia Sepiana'),
                    Text('FAJRUL KAMAL'),
                    Text('GHAZI FARHANU DISASMORO'),
                    Text('HIDAYAH DANIAWATI'),
                    Text('JUHARMANSAH'),
                    Text('KATARINA ANDREA LAURENTIA'),
                    Text('MUHAMMAD AFRIZAL RASYID'),
                    Text('MUHAMMAD ARARYA HAFIZH ATHALLA'),
                    Text('MUHAMMAD ILHAM'),
                    Text('MUHAMMAD NGURAH ARYA PRATAMA'),
                    Text('MUSTIKA CHAIRANI'),
                    Text('NURMALASARI'),
                    Text('Phrimus Nufeto'),
                    Text('PUTRI DIANA HAFSYAWATI'),
                    Text('RACHAEL NATHASYA'),
                    Text('RAFI TAUFIQURAHMAN'),
                    Text('RAMADHAN PUTRA NUGRAHA'),
                    Text('YUNITA ANGGERAINI'),
                    Text('ADE ALI INDRA'),
                    Text('ALWIN ZUHRIANDI MANALU'),
                    Text('ANISA YUNIARTI'),
                    Text('Bima Pangestu Nugraha'),
                    Text('Dastin Pranata Yuda'),
                    Text('David Christian Hui'),
                    Text('David Liem'),
                    Text('Delia Sepiana'),
                    Text('FAJRUL KAMAL'),
                    Text('GHAZI FARHANU DISASMORO'),
                    Text('HIDAYAH DANIAWATI'),
                    Text('JUHARMANSAH'),
                    Text('KATARINA ANDREA LAURENTIA'),
                    Text('MUHAMMAD AFRIZAL RASYID'),
                    Text('MUHAMMAD ARARYA HAFIZH ATHALLA'),
                    Text('MUHAMMAD ILHAM'),
                    Text('MUHAMMAD NGURAH ARYA PRATAMA'),
                    Text('MUSTIKA CHAIRANI'),
                    Text('NURMALASARI'),
                    Text('Phrimus Nufeto'),
                    Text('PUTRI DIANA HAFSYAWATI'),
                    Text('RACHAEL NATHASYA'),
                    Text('RAFI TAUFIQURAHMAN'),
                    Text('RAMADHAN PUTRA NUGRAHA'),
                    Text('YUNITA ANGGERAINI'),
                    Text('ADE ALI INDRA'),
                    Text('ALWIN ZUHRIANDI MANALU'),
                    Text('ANISA YUNIARTI'),
                    Text('Bima Pangestu Nugraha'),
                    Text('Dastin Pranata Yuda'),
                    Text('David Christian Hui'),
                    Text('David Liem'),
                    Text('Delia Sepiana'),
                    Text('FAJRUL KAMAL'),
                    Text('GHAZI FARHANU DISASMORO'),
                    Text('HIDAYAH DANIAWATI'),
                    Text('JUHARMANSAH'),
                    Text('KATARINA ANDREA LAURENTIA'),
                    Text('MUHAMMAD AFRIZAL RASYID'),
                    Text('MUHAMMAD ARARYA HAFIZH ATHALLA'),
                    Text('MUHAMMAD ILHAM'),
                    Text('MUHAMMAD NGURAH ARYA PRATAMA'),
                    Text('MUSTIKA CHAIRANI'),
                    Text('NURMALASARI'),
                    Text('Phrimus Nufeto'),
                    Text('PUTRI DIANA HAFSYAWATI'),
                    Text('RACHAEL NATHASYA'),
                    Text('RAFI TAUFIQURAHMAN'),
                    Text('RAMADHAN PUTRA NUGRAHA'),
                    Text('YUNITA ANGGERAINI'),
                    Text('ADE ALI INDRA'),
                    Text('ALWIN ZUHRIANDI MANALU'),
                    Text('ANISA YUNIARTI'),
                    Text('Bima Pangestu Nugraha'),
                    Text('Dastin Pranata Yuda'),
                    Text('David Christian Hui'),
                    Text('David Liem'),
                    Text('Delia Sepiana'),
                    Text('FAJRUL KAMAL'),
                    Text('GHAZI FARHANU DISASMORO'),
                    Text('HIDAYAH DANIAWATI'),
                    Text('JUHARMANSAH'),
                    Text('KATARINA ANDREA LAURENTIA'),
                    Text('MUHAMMAD AFRIZAL RASYID'),
                    Text('MUHAMMAD ARARYA HAFIZH ATHALLA'),
                    Text('MUHAMMAD ILHAM'),
                    Text('MUHAMMAD NGURAH ARYA PRATAMA'),
                    Text('MUSTIKA CHAIRANI'),
                    Text('NURMALASARI'),
                    Text('Phrimus Nufeto'),
                    Text('PUTRI DIANA HAFSYAWATI'),
                    Text('RACHAEL NATHASYA'),
                    Text('RAFI TAUFIQURAHMAN'),
                    Text('RAMADHAN PUTRA NUGRAHA'),
                    Text('YUNITA ANGGERAINI'),
                    ],)
                )
              ],              
            )
          ),
        ),
                
      )
    );
  }
}